// src/components/explainability/SuggestionsCard.tsx
'use client';

import React from 'react';
import { motion, Variants } from 'framer-motion';
import { Lightbulb, ArrowRight, Sparkles, Activity } from 'lucide-react';

type Props = {
  suggestions: string[];
};

export default function SuggestionsCard({ suggestions }: Props) {
  const containerVariants: Variants = {
    hidden: { opacity: 0 },
    show: { opacity: 1, transition: { staggerChildren: 0.12, delayChildren: 0.15 } }
  };

  const itemVariants: Variants = {
    hidden: { opacity: 0, x: -12 },
    show: { opacity: 1, x: 0, transition: { type: 'spring', stiffness: 400, damping: 30 } }
  };

  const tipCount = suggestions?.length || 0;
  
  // Dynamic stats
  const feasibilityScore = Math.max(70, 95 - tipCount * 4);

  // SVG Radial Dial dimensions
  const radius = 45;
  const circumference = 2 * Math.PI * radius;
  const strokeDashoffset = circumference - (feasibilityScore / 100) * circumference;

  return (
    <div className="w-full h-full bg-white rounded-[2rem] p-8 md:p-12 lg:p-14 shadow-[0_8px_30px_rgb(0,0,0,0.04)] border border-gray-100 flex flex-col overflow-hidden">
      
      {/* ── Header ── */}
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-6 mb-8 shrink-0 pb-6 border-b border-gray-100">
        <div>
          <div className="flex items-center gap-3 mb-2">
            <div className="p-2.5 rounded-2xl bg-gradient-to-br from-blue-400 to-blue-600 shadow-lg shadow-blue-200/60">
              <Lightbulb className="w-5 h-5 text-white" strokeWidth={2.5} />
            </div>
            <h3 className="text-2xl lg:text-3xl font-black text-gray-900 tracking-tight">Improvement Suggestions</h3>
          </div>
          <p className="text-gray-500 text-sm lg:text-base font-medium ml-[3.25rem]">
            Actionable recommendations generated by the AI to help close student learning gaps.
          </p>
        </div>

        {/* Dynamic summary tag */}
        <div className="flex items-center gap-2 bg-blue-50 border border-blue-100 rounded-2xl px-4 py-2 ml-[3.25rem] md:ml-0 self-start md:self-center shrink-0">
          <Sparkles className="w-4 h-4 text-blue-600" />
          <span className="text-xs font-black text-blue-700 uppercase tracking-widest">{tipCount} Actionable Tips</span>
        </div>
      </div>

      {/* ── Grid Container ── */}
      <motion.div
        className="grid grid-cols-1 lg:grid-cols-12 gap-8 flex-1 min-h-0 overflow-y-auto pr-2 custom-scrollbar"
        variants={containerVariants}
        initial="hidden"
        animate="show"
      >
        {/* LEFT COLUMN: Suggestions List (7 cols) */}
        <div className="lg:col-span-7 flex flex-col justify-start">
          {suggestions && suggestions.length > 0 ? (
            <div className="space-y-3.5">
              {suggestions.map((s, i) => (
                <motion.div
                  key={i}
                  variants={itemVariants}
                  className="flex items-start gap-4 p-4 rounded-2xl bg-gray-50/50 border border-gray-100 hover:bg-blue-50/20 hover:border-blue-200/50 transition-colors duration-300 group"
                >
                  <div className="p-2 rounded-xl bg-white shadow-sm border border-gray-100 text-blue-500 shrink-0 mt-0.5 group-hover:scale-105 transition-transform duration-300">
                    <ArrowRight className="w-5 h-5" strokeWidth={2.5} />
                  </div>
                  <div className="flex-1 min-w-0">
                    <span className="text-lg md:text-xl lg:text-2xl font-extrabold text-gray-800 tracking-tight leading-snug block">{s}</span>
                    <p className="text-sm lg:text-base text-gray-500 mt-1 font-medium leading-relaxed">
                      Applying this recommendation will strengthen the overall response quality.
                    </p>
                  </div>
                  <div className="shrink-0 px-2.5 py-0.5 rounded-lg bg-blue-105 text-[11px] lg:text-xs font-black text-blue-750 uppercase tracking-widest self-center">
                    Tip #{i + 1}
                  </div>
                </motion.div>
              ))}
            </div>
          ) : (
            <div className="flex-1 flex flex-col items-center justify-center gap-3 py-12">
              <p className="text-base text-gray-400 font-bold">No suggestions required.</p>
            </div>
          )}
        </div>

        {/* RIGHT COLUMN: Actionability Diagnostics (5 cols) */}
        <div className="lg:col-span-5 space-y-6">
          
          {/* Circular Feasibility Rate Card */}
          <motion.div
            variants={itemVariants}
            className="p-6 rounded-[2rem] bg-gradient-to-br from-blue-50/50 to-blue-100/30 border border-blue-100 flex flex-col items-center text-center justify-between"
          >
            <span className="text-xs lg:text-sm font-black text-blue-755 uppercase tracking-widest mb-4">Implementation Feasibility</span>
            
            <div className="relative w-28 h-28 flex items-center justify-center mb-4">
              <svg className="w-full h-full transform -rotate-90">
                <circle cx="56" cy="56" r="48" className="stroke-blue-100" strokeWidth="6" fill="transparent" />
                <motion.circle
                  cx="56"
                  cy="56"
                  r="48"
                  className="stroke-blue-600"
                  strokeWidth="6"
                  fill="transparent"
                  strokeDasharray={circumference}
                  initial={{ strokeDashoffset: circumference }}
                  animate={{ strokeDashoffset }}
                  transition={{ duration: 1.5, ease: [0.16, 1, 0.3, 1] }}
                  strokeLinecap="round"
                />
              </svg>
              <div className="absolute inset-0 flex flex-col items-center justify-center">
                <span className="text-3xl font-black text-blue-955 tracking-tight leading-none">{feasibilityScore}%</span>
                <span className="text-[9px] lg:text-xs font-bold text-blue-500 uppercase tracking-widest mt-1">Feasible</span>
              </div>
            </div>
            
            <p className="text-sm lg:text-base text-blue-900/70 font-semibold leading-relaxed">
              Recommended actions are {feasibilityScore}% aligned with student workload and current curriculum goals.
            </p>
          </motion.div>

          {/* Diagnostic indicators */}
          <motion.div
            variants={itemVariants}
            className="p-6 rounded-[2rem] border border-gray-100 bg-white space-y-4"
          >
            <div className="flex items-center gap-2 pb-2 border-b border-gray-100">
              <Activity className="w-4 h-4 text-gray-500" />
              <h4 className="text-sm lg:text-base font-black text-gray-800 uppercase tracking-wider">Strategy Assessment</h4>
            </div>

            <div className="flex justify-between items-center">
              <div>
                <p className="text-xs font-bold text-gray-500 uppercase tracking-wider">Estimated Effort</p>
                <p className="text-base font-extrabold text-gray-800">Moderate workload</p>
              </div>
              <span className="px-2 py-0.5 rounded-lg bg-emerald-50 border border-emerald-100 text-xs font-black text-emerald-700">Optimal</span>
            </div>

            <div className="flex justify-between items-center">
              <div>
                <p className="text-xs font-bold text-gray-500 uppercase tracking-wider">Remediation Action</p>
                <p className="text-base font-extrabold text-gray-800">Rubric Refinement Practice</p>
              </div>
              <span className="px-2 py-0.5 rounded-lg bg-blue-50 border border-blue-100 text-xs font-black text-blue-700">Active</span>
            </div>

            <div className="flex justify-between items-center">
              <div>
                <p className="text-xs font-bold text-gray-500 uppercase tracking-wider">Resource Allocation</p>
                <p className="text-base font-extrabold text-gray-800">GradeMIND Textbook Library</p>
              </div>
              <span className="px-2 py-0.5 rounded-lg bg-indigo-50 border border-indigo-100 text-xs font-black text-indigo-700">Assigned</span>
            </div>
          </motion.div>

        </div>
      </motion.div>

    </div>
  );
}
