"use client";

import React from "react";
import { cn } from "@/utils/cn";
import { Sparkles, BarChart3, UploadCloud, ShieldCheck } from "lucide-react";
import { BorderBeam } from "./border-beam";

export interface PageHeroBannerProps {
  badgeLabel?: string;
  badgeIcon?: React.ReactNode;
  title: string;
  subtitle: string;
  statLabel?: string;
  statValue?: string;
  actionButton?: React.ReactNode;
  className?: string;
}

export const PageHeroBanner: React.FC<PageHeroBannerProps> = ({
  badgeLabel = "ANALYTICAL REPORTS REPOSITORY",
  badgeIcon = <BarChart3 className="w-3.5 h-3.5 text-emerald-400" />,
  title = "Scorecards & Evaluated Reports",
  subtitle = "Browse, search, and download candidate scorecard PDFs generated by Groq 120B AI.",
  statLabel = "TOTAL EVALUATED",
  statValue = "7 Reports",
  actionButton,
  className = "",
}) => {
  return (
    <div
      className={cn(
        "relative w-full rounded-2xl md:rounded-3xl bg-gradient-to-r from-[#183B25] via-[#112B1B] to-[#183B25] text-white p-6 md:p-8 shadow-xl overflow-hidden border-2 border-emerald-700/40 flex flex-col md:flex-row md:items-center justify-between gap-6",
        className
      )}
    >
      <BorderBeam colorFrom="#4A8B40" colorTo="#74A86D" duration={8} />

      {/* Left Text Column */}
      <div className="space-y-3 max-w-2xl text-left z-10">
        <div className="inline-flex items-center gap-2 px-3.5 py-1 rounded-full bg-[#0F2618]/90 border border-emerald-500/50 text-emerald-300 text-[11px] font-black uppercase tracking-wider shadow-xs">
          {badgeIcon}
          <span>{badgeLabel}</span>
        </div>

        <h1 className="text-2xl md:text-4xl font-black tracking-tight text-white font-sans">
          {title}
        </h1>

        <p className="text-xs md:text-sm font-bold text-emerald-100/90 leading-relaxed max-w-xl">
          {subtitle}
        </p>
      </div>

      {/* Right Column: Stat Badge / Action */}
      <div className="flex items-center gap-4 shrink-0 z-10">
        {actionButton}

        {statValue && (
          <div className="px-6 py-4 rounded-2xl bg-[#0F2618]/90 border border-emerald-600/60 shadow-inner flex flex-col items-center justify-center min-w-[150px]">
            <span className="text-[10px] font-black text-emerald-300 uppercase tracking-widest block mb-1">
              {statLabel}
            </span>
            <span className="text-xl md:text-2xl font-black text-emerald-400 tracking-tight">
              {statValue}
            </span>
          </div>
        )}
      </div>
    </div>
  );
};
