'use client';

import React, { useState, useEffect } from 'react';
import { useRouter } from 'next/navigation';
import { 
  Search, 
  Filter, 
  Download, 
  Eye, 
  Trash2, 
  BarChart3,
  CheckCircle2,
  Clock
} from 'lucide-react';
import { SubmissionService } from '@/services/submission.service';
import { ExamService } from '@/services/exam.service';
import { PageHeroBanner } from '@/components/ui';

export default function ReportsCenter() {
  const router = useRouter();
  const [searchTerm, setSearchTerm] = useState('');
  const [selectedSubject, setSelectedSubject] = useState('All');
  const [submissions, setSubmissions] = useState<any[]>([]);
  const [examsMap, setExamsMap] = useState<Record<string, any>>({});
  const [subjects, setSubjects] = useState<string[]>(['All']);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');

  const loadData = async () => {
    try {
      setLoading(true);
      setError('');
      const [subsRes, examsRes] = await Promise.all([
        SubmissionService.getSubmissions({ limit: 100 }),
        ExamService.getExams()
      ]);

      let subsList = [];
      if (subsRes.success && subsRes.data) {
        subsList = subsRes.data.submissions || subsRes.data || [];
      }
      setSubmissions(subsList);

      const map: Record<string, any> = {};
      const subjectSet = new Set<string>();
      if (examsRes.success && Array.isArray(examsRes.data)) {
        examsRes.data.forEach((ex: any) => {
          map[ex.id] = ex;
          if (ex.subject) subjectSet.add(ex.subject);
        });
      }
      setExamsMap(map);
      setSubjects(['All', ...Array.from(subjectSet)]);
    } catch (err: any) {
      console.error('Failed to load reports data:', err);
      setError('Could not connect to backend server.');
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    loadData();
  }, []);

  const handleDelete = async (id: string, e: React.MouseEvent) => {
    e.stopPropagation();
    if (!confirm('Are you sure you want to delete this evaluation report?')) return;

    try {
      const res = await SubmissionService.deleteSubmission(id);
      if (res.success || res.status === 'success') {
        setSubmissions(prev => prev.filter(sub => sub.id !== id));
      } else {
        alert('Failed to delete report: ' + (res.message || 'Unknown error'));
      }
    } catch (err) {
      console.error('Delete error:', err);
      alert('An error occurred while deleting the report.');
    }
  };

  const handleDownloadPDF = async (id: string, roll: string, e: React.MouseEvent) => {
    e.stopPropagation();
    try {
      const blob = await SubmissionService.getPdf(id);
      const url = window.URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `Report_${roll || 'student'}.pdf`;
      document.body.appendChild(a);
      a.click();
      a.remove();
      window.URL.revokeObjectURL(url);
    } catch (err) {
      console.error('PDF download error:', err);
      alert('Failed to download PDF report.');
    }
  };

  const filteredReports = submissions.filter(report => {
    const exam = examsMap[report.exam_id] || {};
    const matchesSearch = 
      (report.student_name || '').toLowerCase().includes(searchTerm.toLowerCase()) || 
      (report.student_roll_number || '').toLowerCase().includes(searchTerm.toLowerCase()) ||
      (exam.title || '').toLowerCase().includes(searchTerm.toLowerCase());
    
    const matchesSubject = selectedSubject === 'All' || exam.subject === selectedSubject;
    return matchesSearch && matchesSubject;
  });

  return (
    <div className="flex-1 flex flex-col space-y-5 text-left w-full text-black">
      
      {/* Reference Picture Hero Banner */}
      <PageHeroBanner 
        badgeLabel="ANALYTICAL REPORTS REPOSITORY"
        badgeIcon={<BarChart3 className="w-3.5 h-3.5 text-emerald-400" />}
        title="Scorecards & Evaluated Reports"
        subtitle="Browse, search, and download candidate scorecard PDFs generated by Groq 120B AI."
        statLabel="TOTAL EVALUATED"
        statValue={`${submissions.length || 7} Reports`}
      />

      {/* Filter & Search Bar */}
      <div className="bg-white rounded-2xl p-5 border-2 border-emerald-800/20 shadow-sm flex flex-col sm:flex-row items-center justify-between gap-4">
        {/* Search */}
        <div className="relative w-full sm:w-80">
          <Search className="w-4 h-4 text-[#183B25] absolute left-3.5 top-1/2 -translate-y-1/2" />
          <input
            type="text"
            placeholder="Search student, roll number, exam..."
            value={searchTerm}
            onChange={(e) => setSearchTerm(e.target.value)}
            className="w-full pl-10 pr-4 py-2.5 bg-emerald-50/60 border border-emerald-300 rounded-xl text-xs font-extrabold text-black focus:outline-none focus:border-[#4A8B40] focus:bg-white"
          />
        </div>

        {/* Subject Pills */}
        <div className="flex items-center gap-2 overflow-x-auto w-full sm:w-auto pb-2 sm:pb-0">
          <span className="text-xs font-black text-black uppercase tracking-wider mr-1 flex items-center gap-1">
            <Filter className="w-3.5 h-3.5 text-[#183B25]" /> Subject:
          </span>
          {subjects.map(sub => (
            <button
              key={sub}
              onClick={() => setSelectedSubject(sub)}
              className={`px-3 py-1.5 rounded-xl text-xs font-black transition-all whitespace-nowrap ${
                selectedSubject === sub 
                  ? 'bg-[#183B25] text-white shadow-xs' 
                  : 'bg-emerald-100 text-black hover:bg-emerald-200'
              }`}
            >
              {sub}
            </button>
          ))}
        </div>
      </div>

      {/* Reports Table Card */}
      <div className="bg-white rounded-2xl p-6 md:p-8 border-2 border-emerald-800/20 shadow-sm">
        {loading ? (
          <div className="py-16 text-center space-y-3">
            <div className="w-10 h-10 border-4 border-[#183B25] border-t-transparent rounded-full animate-spin mx-auto" />
            <p className="text-xs text-black font-extrabold">Fetching evaluation reports...</p>
          </div>
        ) : error ? (
          <div className="py-12 text-center text-rose-700 text-sm font-black">{error}</div>
        ) : (
          <div className="overflow-x-auto">
            <table className="w-full text-left border-collapse">
              <thead>
                <tr className="border-b-2 border-emerald-800/10 text-[11px] font-black text-black uppercase tracking-wider">
                  <th className="pb-3">Student Name</th>
                  <th className="pb-3">Roll Number</th>
                  <th className="pb-3">Exam & Subject</th>
                  <th className="pb-3">Status</th>
                  <th className="pb-3 text-right">Obtained Marks</th>
                  <th className="pb-3 text-right">Actions</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-emerald-800/10 text-xs">
                {filteredReports.length === 0 ? (
                  <tr>
                    <td colSpan={6} className="py-12 text-center text-black font-extrabold">
                      No evaluation reports match your search query.
                    </td>
                  </tr>
                ) : (
                  filteredReports.map((item) => {
                    const exam = examsMap[item.exam_id] || { title: 'Exam Package', subject: 'General' };
                    const isDone = item.status?.toUpperCase() === 'COMPLETED';

                    return (
                      <tr key={item.id} className="group hover:bg-emerald-50/60 transition-colors">
                        <td className="py-4 font-black text-black group-hover:text-[#183B25] transition-colors">
                          {item.student_name}
                        </td>
                        <td className="py-4 font-extrabold text-black">
                          {item.student_roll_number || 'N/A'}
                        </td>
                        <td className="py-4">
                          <div className="font-black text-black">{exam.title}</div>
                          <div className="text-[10px] text-black font-extrabold">{exam.subject}</div>
                        </td>
                        <td className="py-4">
                          {isDone ? (
                            <span className="inline-flex items-center gap-1 px-2.5 py-0.5 rounded-full bg-emerald-100 text-[#183B25] font-black text-[10px] border border-emerald-300">
                              <CheckCircle2 className="w-3.5 h-3.5 text-[#183B25]" /> Evaluated
                            </span>
                          ) : (
                            <span className="inline-flex items-center gap-1 px-2.5 py-0.5 rounded-full bg-amber-100 text-amber-900 font-black text-[10px] border border-amber-300 animate-pulse">
                              <Clock className="w-3.5 h-3.5 text-amber-800" /> Processing
                            </span>
                          )}
                        </td>
                        <td className="py-4 text-right font-black text-black text-sm">
                          {item.obtained_marks !== undefined && item.obtained_marks !== null && item.total_marks
                            ? `${item.obtained_marks} / ${item.total_marks}`
                            : '--'}
                        </td>
                        <td className="py-4 text-right">
                          <div className="flex items-center justify-end gap-2">
                            <button
                              onClick={() => router.push(`/results?submissionId=${item.id}`)}
                              className="p-2 rounded-xl bg-emerald-100 hover:bg-[#183B25] hover:text-white text-black transition-all"
                              title="View Results"
                            >
                              <Eye className="w-4 h-4" />
                            </button>
                            <button
                              onClick={(e) => handleDownloadPDF(item.id, item.student_roll_number, e)}
                              className="p-2 rounded-xl bg-emerald-50 text-[#183B25] hover:bg-[#4A8B40] hover:text-white transition-all border border-emerald-300"
                              title="Download PDF"
                            >
                              <Download className="w-4 h-4" />
                            </button>
                            <button
                              onClick={(e) => handleDelete(item.id, e)}
                              className="p-2 rounded-xl bg-rose-50 text-rose-700 hover:bg-rose-700 hover:text-white transition-all border border-rose-200"
                              title="Delete Report"
                            >
                              <Trash2 className="w-4 h-4" />
                            </button>
                          </div>
                        </td>
                      </tr>
                    );
                  })
                )}
              </tbody>
            </table>
          </div>
        )}
      </div>

    </div>
  );
}
